"use strict";
const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");
const express = require("express");
const attach = require("../admin-api");
test("publishing validates, authenticates, persists and detects conflicts", async t => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), "ptg-status-"));
    const file = path.join(dir, "status.json");
    const original = { publishedAt: "2026-09-01T00:00:00Z", services: [{id:"vpn", name:"VPN",status:"operational"}], incidents:[],maintenance:[],supportUrls:{vpn:"https://example.com/support"} };
    await fs.writeFile(file, JSON.stringify(original));
    const key = "test-only-key-for-publishing-12345";
    const app = express(); app.use(express.json()); attach(app,{statusFile:file,key});
    const server = app.listen(0,"127.0.0.1");
    await new Promise(resolve=>server.once("listening",resolve));
    t.after(async()=>{await new Promise(resolve=>server.close(resolve)); await fs.unlink(file); await fs.rmdir(dir);});
    const url = "http://127.0.0.1:" + server.address().port + "/api/admin/status";
    const send=(method="GET",body,extra={})=>fetch(url,{method,headers:{Authorization:"Bearer "+key,"Content-Type":"application/json",...extra},...(body?{body:JSON.stringify(body)}:{})});
    assert.equal((await fetch(url)).status,401);
    assert.equal((await send("GET",null,{Authorization:"Bearer wrong"})).status,401);
    const snapshot=await (await send()).json();
    assert.equal((await send("PUT",{...snapshot},{Origin:"https://attacker.example"})).status,403);
    const bad=structuredClone(snapshot);bad.data.services[0].status="invented";
    assert.equal((await send("PUT",bad)).status,400);
    const invalidEvent=structuredClone(snapshot);
    invalidEvent.data.maintenance=[{id:"m",serviceId:"vpn",title:"Upgrade",message:"Brief interruption",start:"2026-09-20T12:00:00Z",end:"2026-09-20T11:00:00Z"}];
    assert.equal((await send("PUT",invalidEvent)).status,400);
    const duplicate=structuredClone(snapshot);duplicate.data.services.push(duplicate.data.services[0]);
    assert.equal((await send("PUT",duplicate)).status,400);
    assert.deepEqual(JSON.parse(await fs.readFile(file,"utf8")),original);
    snapshot.data.services[0].status="degraded";
    snapshot.data.incidents=[{id:"i",serviceId:"vpn",title:"VPN slow",message:"Investigating",start:"2026-09-16T12:00:00Z"}];
    snapshot.data.maintenance=[{id:"m",serviceId:"vpn",title:"Upgrade",message:"Brief interruption",start:"2026-09-20T12:00:00Z",end:"2026-09-20T13:00:00Z"}];
    const response=await send("PUT",snapshot);assert.equal(response.status,200);
    const saved=await response.json();assert.notEqual(saved.revision,snapshot.revision);
    assert.equal(saved.data.services[0].statusText,"Degraded performance");
    assert.equal(saved.data.incidents[0].service,"VPN");
    assert.equal(saved.data.maintenance[0].status,"maintenance");
    assert.deepEqual(saved.data.supportUrls,original.supportUrls);
    assert.deepEqual(JSON.parse(await fs.readFile(file,"utf8")),saved.data);
    assert.equal((await send("PUT",snapshot)).status,409);
    saved.data.incidents[0].phase="resolved";saved.data.incidents[0].pendingUpdate="Connectivity restored.";saved.data.maintenance=[];saved.data.services[0].status="operational";

    const resolution = await send("PUT",saved);
    assert.equal(resolution.status,200);
    const resolved = await resolution.json();
    assert.equal(resolved.data.incidents[0].phase,"resolved");
    assert.equal(resolved.data.incidents[0].updates.length,2);
    assert.equal(resolved.data.incidents[0].updates[1].message,"Connectivity restored.");
    const correction = structuredClone(resolved);
    correction.data.incidents[0].updateCorrections=[{id:correction.data.incidents[0].updates[0].id,message:"Investigating VPN connectivity.",phase:"investigating",impact:"unknown",workaround:"",nextUpdateAt:""}];
    const correctedResponse=await send("PUT",correction);assert.equal(correctedResponse.status,200);
    const corrected=await correctedResponse.json();
    assert.equal(corrected.data.incidents[0].updates[0].message,"Investigating VPN connectivity.");
    assert.equal(corrected.data.incidents[0].updates[0].at,resolved.data.incidents[0].updates[0].at);
    assert.equal(corrected.data.incidents[0].updateCorrections,undefined);
    const invalidCorrection=structuredClone(corrected);
    invalidCorrection.data.incidents[0].updateCorrections=[{id:"unknown",message:"Forged correction",phase:"investigating",impact:"unknown",workaround:"",nextUpdateAt:""}];
    assert.equal((await send("PUT",invalidCorrection)).status,400);
    const deletion=structuredClone(corrected);
    deletion.data.incidents[0].deletedUpdateIds=[deletion.data.incidents[0].updates[1].id];
    const deletionResponse=await send("PUT",deletion);assert.equal(deletionResponse.status,200);
    const trimmed=await deletionResponse.json();
    assert.equal(trimmed.data.incidents[0].updates.length,1);
    assert.equal(trimmed.data.incidents[0].updates[0].message,"Investigating VPN connectivity.");
    assert.equal(trimmed.data.incidents[0].deletedUpdateIds,undefined);
    const invalidDeletion=structuredClone(trimmed);
    invalidDeletion.data.incidents[0].deletedUpdateIds=["unknown"];
    assert.equal((await send("PUT",invalidDeletion)).status,400);
    const deleted = structuredClone(trimmed); deleted.data.incidents = [];
    assert.equal((await send("PUT",deleted)).status,400);
    const invalidImpact = structuredClone(trimmed);
    invalidImpact.data.microsoftAssessments=[{id:"MS1",impact:"invented"}];
    assert.equal((await send("PUT",invalidImpact)).status,400);
    trimmed.data.microsoftAssessments=[{id:"MS1",impact:"confirmed",note:"Staff affected."}];
    trimmed.data.incidents[0].updates=[{id:"fake",at:"2000-01-01",message:"Forged update"}];
    const assessedResponse = await send("PUT",trimmed);
    assert.equal(assessedResponse.status,200);
    const assessed = await assessedResponse.json();
    assert.equal(assessed.data.microsoftAssessments[0].impact,"confirmed");
    assert.equal(assessed.data.incidents[0].updates.length,1);
    assert.equal(assessed.data.incidents[0].updates[0].message,"Investigating VPN connectivity.");

});
test("public pages work, private files are blocked, and local status reaches API", async t => {
    process.env.AZURE_TENANT_ID="";process.env.AZURE_CLIENT_ID="";process.env.AZURE_CLIENT_SECRET="";process.env.ADMIN_API_KEY="";process.env.FRESHSERVICE_DOMAIN="";process.env.FRESHSERVICE_API_KEY="";process.env.FRESHSERVICE_REQUESTER_EMAIL="";
    const isolated = await fs.mkdtemp(path.join(os.tmpdir(), "ptg-public-"));
    const fixture = path.join(isolated, "status.json");
    await fs.writeFile(fixture, JSON.stringify({ services: [{id:"vpn", name:"VPN", status:"operational"}], incidents:[], maintenance:[] }));
    process.env.STATUS_FILE=fixture; process.env.USERS_FILE=path.join(isolated,"users.json"); process.env.STORAGE_DRIVER="file";
    t.after(async()=>{ await fs.unlink(fixture); await fs.rmdir(isolated); delete process.env.USERS_FILE; });
    const app=require("../server");
    const server=app.listen(0,"127.0.0.1");
    await new Promise(resolve=>server.once("listening",resolve));
    t.after(()=>new Promise(resolve=>server.close(resolve)));
    const base="http://127.0.0.1:"+server.address().port;
    for(const route of ["/","/admin/","/style.css","/admin/app.js"]) assert.equal((await fetch(base+route)).status,200,route);
    for(const route of ["/.env","/server.js","/admin-api.js","/package.json","/node_modules/express/package.json","/status.json","/users.json","/storage.js","/database/setup.sql","/database-setup.js"]) assert.equal((await fetch(base+route)).status,404,route);
    assert.equal((await fetch(base+"/api/admin/status")).status,503);
    const result=await (await fetch(base+"/api/status")).json();
    assert.equal(result.microsoftAvailable,false);
    assert.equal(result.services.length,new Set(result.services.map(s=>s.id)).size);
    assert.ok(result.services.some(s=>s.id==="vpn"));
    assert.ok(result.services.filter(s=>s.source==="Microsoft").every(s=>s.status==="unknown"));
});

test("service creation, edits and removal preserve linked history", async t => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), "ptg-catalog-"));
    const file = path.join(dir,"status.json");
    await fs.writeFile(file, JSON.stringify({services:[],incidents:[],maintenance:[]}));
    const key="catalog-test-key-at-least-24-characters";
    const app=express(); app.use(express.json()); attach(app,{statusFile:file,key});
    const server=app.listen(0,"127.0.0.1");
    await new Promise(resolve=>server.once("listening",resolve));
    t.after(async()=>{await new Promise(resolve=>server.close(resolve));await fs.unlink(file);await fs.rmdir(dir);});
    const url="http://127.0.0.1:"+server.address().port+"/api/admin/status";
    let snapshot=await (await fetch(url,{headers:{Authorization:"Bearer "+key}})).json();
    const put=body=>fetch(url,{method:"PUT",headers:{Authorization:"Bearer "+key,"Content-Type":"application/json"},body:JSON.stringify(body)});
    const save=async()=>{const r=await put(snapshot);assert.equal(r.status,200,await r.clone().text());snapshot=await r.json();};
    snapshot.data.services.push({id:"printing",name:"Printing",description:"Office printers",status:"operational"});
    await save();
    assert.equal(snapshot.data.services[0].description,"Office printers");
    for(const patch of [{id:"identity"},{name:" "},{description:"x".repeat(501)}]){
        const invalid=structuredClone(snapshot);Object.assign(invalid.data.services[0],patch);
        assert.equal((await put(invalid)).status,400);
    }
    snapshot.data.incidents=[{id:"print-incident",serviceId:"printing",title:"Printing delayed",message:"Investigating queues",start:"2026-09-17T10:00:00Z",phase:"investigating"}];
    await save();
    let removal=structuredClone(snapshot);removal.data.services=[];
    assert.equal((await put(removal)).status,400);
    snapshot.data.services[0].name="Office printing";snapshot.data.services[0].status="degraded";
    await save();assert.equal(snapshot.data.incidents[0].service,"Office printing");
    snapshot.data.incidents[0].phase="resolved";
    snapshot.data.maintenance=[{id:"upgrade",serviceId:"printing",title:"Upgrade",message:"Updating printers",start:"2026-09-20T10:00:00Z",end:"2026-09-20T11:00:00Z"}];
    await save();
    removal=structuredClone(snapshot);removal.data.services=[];
    assert.equal((await put(removal)).status,400);
    snapshot.data.maintenance=[];snapshot.data.services=[];
    await save();assert.equal(snapshot.data.incidents[0].service,"Office printing");
    assert.equal(snapshot.data.retiredServices[0].id,"printing");
    await save();assert.equal(snapshot.data.incidents[0].phase,"resolved");
    const reuse=structuredClone(snapshot);reuse.data.services=[{id:"printing",name:"Different printing",status:"operational"}];
    assert.equal((await put(reuse)).status,400);
    const reopen=structuredClone(snapshot);reopen.data.incidents[0].phase="investigating";
    assert.equal((await put(reopen)).status,400);
    const forged=structuredClone(snapshot);forged.data.incidents.push({...forged.data.incidents[0],id:"forged"});
    assert.equal((await put(forged)).status,400);
});
